# Поддерживается MarkdownV2 для парсинга строк
# \n - перевод на новую строку
# *{text}* - выделение текста жирным
# {} - вставка дополнительного текста в зависимости от условий

# Сообщения команды /start
start:
  # Первое сообщение которое видят пользователи когда нажали на /start
  first: "Привет! Ты подписался на бота @trip_for_students ☺️ \nЭто значит, что совсем скоро мы вместе отправимся в путешествие или наоборот вернемся из него \n\nПожалуйста, отправь свой номер телефона, чтобы мы могли найти тебя в списках путешественников, а бот - отправлять сообщения 😇 \n С любовью из всех уголков России,\nтвои лучшие путешествия 🧡"
  # Сообщение если пользователь уже подписан на бот
  if_exist: "Ты уже подписан на нашу рассылку, но у нас пока нет сообщений для тебя😢\nЛови котика, чтобы не было так грустно"
  # Добавочное сообщение к сообщению {if_exist} если пользователь подписан, но не поделился телефоном
  if_exist_without_phone: "Правда, у нас все еще нет твоего номера :( \nБоту будет трудно найти тебя без него😔\n\nДавай исправим это? Просто тыкай на кнопку ниже🧡"
  # Сообщение о том что бот успешно сохранил телефон
  complete_save: "Спасибо мы сохранили ваш номер 🧡"

# Сообщения команды /help
help:
  # Сообщение для всех в /help
  message: 'Вот, что ты можешь делать: \n'
  # Команды доступные пользователям и их описание краткое
  user:
    # Сначала строчка с названием команды, потом строка с описанием
    - start
    - 'Подписаться на рассылку ✉️'
    - help
    - 'Получить информацию о доступных командах ℹ️'
    - tours
    - 'Получить информацию о ближайших турах (скоро)'
  # Команды доступные администраторам и их описание краткое
  # Описание команды start и help берется из описания для пользователей
  admin:
    - mail
    - 'Создает новую рассылку сообщений по пользователям'
    - users
    - 'Получение пользователей подписанных на рассылку'
    - admins
    - 'Изменить администраторов'

# Сообщения команды /users
# todo: на будущее лучше сделать не в боте вывод этой информации,
#  а например через простой web интерфейс
users:
  # Название колонок в таблице с пользователями
  columns:
    - Name
    - Number
    - Admin
  # {0} - количество пользователей
  # {1} - таблица с колонками и информацией о пользователях
  message: "Количество пользователей в базе: {0}\n\n{1}"

# Сообщения команды /admins
admins:
  first: "Что бы хотите сделать?"
  # Сообщение, если вы выбрали добавить нового администратора
  create_admin: "Введите имя пользователя (он должен уже быть подписан на меня!)"
  # Сообщение, если вы выбрали удалить права администратора, у одного из пользователей
  delete_admin: "Выберите пользователя у которого хотите убрать права администратора:"
  # Сообщение, если вы выбрали, что хотите отнять у кого то права администратора, но таких пользователей кроме вас нет
  no_users: "Нет пользователей которых можно понизить:D"
  # Сообщение об ошибке когда попытался добавить администратора, а такого пользователя в системе нет
  # {0} - подставляется имя пользователя введенное вами
  fail_not_subscribe: "Нет пользователя под именем {0}, который был бы на меня подписан"
  # Сообщение, когда выбранный вами пользователь успешно лишен прав администратора
  # {0} - имя  пользователя
  take_away_admin: "Пользователь {0} лишен прав администратора!"
  # Сообщение о том что пользователь повышен до администратора
  # {0} - подставляется имя пользователя которого вы повысили до администратора
  success: "Пользователь {0} успешно повышен до администратора!"

# Сообщения команды /users
mail:
  # Первое сообщение
  first: "Перед началом рассылки введите сообщение для рассылки:"
  # Сообщение с подтверждением о введенном сообщение для рассылки
  # {0} - вставляется введенный текст сообщения для проверки
  verify_msg: "Вы уверены что хотите разослать это сообщение:\n\n{0}"
  # Сообщение, которое появляется если вы не подтвердили сообщение для рассылки которое ввели
  cancel_msg: "Введите сообщение по новой!"
  # Сообщение, которое появляется, если вы подтвердили сообщение для рассылки которое ввели
  accept_msg: "Теперь загрузите ваш xlsx файл 🧡"
  # Сообщение, когда присланный файл неверного формата
  bad_format_file: "Вы прислали файл не правильного формата, попробуйте снова:3"
  # Сообщение, об ошибке когда выбранное вами поле не найдено в excel
  # {0} - название поля
  xlsx_column_fail: "При проверке xlsx, файла произошла ошибка,\nвыбранное вами поле {0} не присутствует в xlsx файле.\nПопробуйте снова, чуть позже, я пока сообщу администратору."
  # Сообщение, после загрузки файла, когда надо выбрать колонку содержащую номер телефона
  choose_column_name: "Теперь выберите колонку которая содержит *номер пользователя*:"
  # Сообщение, когда какие-то данные не получилось получить из excel
  # {0} - список номеров которые не удалось получить из excel
  # {1} - количество пользователей которых удалось, получить excel
  # {2} - количество пользователей которых не удалось, получить из excel
  bad_data: "При проверке xlsx файла, произошла ошибка при валидации этих пользователей:\n{0}\nВсё ещё хотите сделать рассылку на оставшихся пользователей? {1}/{2}"
  # Сообщение, когда не все пользователи из excel, подписаны на бота
  # {0} - список пользователей которые не подписаны на бот
  # {1} - количество подписанных пользователей
  # {2} - общее количество пользователей
  not_subs: "Некоторые из пользователей не подписаны на меня:\n{0}\nВы хотите сделать рассылку на оставшихся пользователей? {1}/{2}"
  # Сообщение, когда ни один из пользователей не подписан на бота
  not_subs_all: "Никто из списка пользователей на меня не подписан:c\nСначала попросите их подписаться, а потом делайте рассылку!🧡"
  # Сообщение, подтверждение перед рассылкой, если все пользователи подписаны на бота
  pre_send_msg: "Все пользователи полученные в файле подписаны на меня 🧡\nНачинаю рассылку?"
  # Сообщение, когда вы отменили отправку, например из-за того что только 5 пользователей из 15 было подписано
  error_msg: "Значит как только всё будет готово возвращайтесь к нам снова и начинайте сначала!"
  # Финальное сообщение после всех действий
  # {0} - количество отправленных сообщений
  # {1} - изначальное количество сообщений которое должно быть разослано
  final_msg: "Сообщения разосланы: {0}/{1}"
# Стандартные сообщения
default_msg:
  # Ошибка в момент когда пользователь попытался перепрыгнуть какие-то шаги, и например сразу загрузил файл:/
  stage_fail: "Что-то произошло на сервере, попробуйте начать сначала:c"

buttons:
  # Текст кнопки для того что бы поделится телефоном
  send_phone: "Поделится телефоном"
  # Текст кнопки для добавления администратора
  add_admin: "Добавить администратора"
  # Текст кнопки для удаления администратора
  delete_admin: "Удалить администратора"

  # Стандартные сообщения для кнопок с подтверждением действий
  default_yes: "Да"
  default_no: "Нет"